### ISSUE TITLE
Load partially saved survey no longer retrieves photos

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/pacific-emis-education-survey-tool#55]
I believe this used to work. We could use the feature Load partially saved survey to retrieve a survey from the cloud onto another tablet (say a tablet is lost, etc.). It works but the photos are all blank. This one I tried to retrieve an older created cloudfile from production. But this can easily be reproduced in Development (which I did and result was the same). Why?

![Screenshot 2022-10-12 114500](https://user-images.githubusercontent.com/1091769/195284821-03c4cd5a-af93-4850-9708-bdfe666788d7.jpg)

**Comment by ghachey** [comment]
This seems to be working again in latest. Can close when merging code base.

**Comment by ghachey** [comment]
This seems to be not working is the latest shared est-03.10.23-release.apk. Is this fixed? It is not an urgent blocking issue. Or perhaps it is working but taking a long time to load? Please do further testing on a test survey with at least 500 images. 

1. Create a new test school accreditation survey in Development mode. Complete it and make sure there is 1 to a few photos for each sub-criteria. Total of around 500 photos minimum. 
2. Try to retrieve on another different tablet this survey using the "Load partially saved survey" feature.
3. Look to make sure all photos are actually also in the new tablet along with the loaded survey.

**Comment by ghachey** [comment]
Correction. This does seem to work now. Observed issue may be relate to something else. Perhaps the photos are no longer in the cloud account deleted somehow?! In either case, I believe this issue as originally filed is fixed.

**Comment by ghachey** [comment]
@maratomega please confirm this was part of the most recent shared build and then we close.

**Comment by maratomega** [comment]
@ghachey fixed in the most recent shared build
