### ISSUE TITLE
Add support for additional stricter validation to consider a survey completed

### ISSUE THREAD

**Issue by ghachey** [PacificEMIS/pacific-emis-education-survey-tool#57]
All of this is not final and only here for consideration, discussion and eventually finalize into requirements specifications.

Add support for additional stricter validation to consider a survey as completed. Currently comments, photos, running record are all optional and a survey is considered completed when all sub-criteria questions have been answered. Some to consider are:

- Minimum of 2 photos per sub-criteria. Here are some things to consider when discussing this: what about sub-criteria that does not make sense to have photo evidence? what about sub-criteria answered as No, why provide evidence of non-compliance?
- Minimum of one comment.
- Running record. What is considered an acceptable running record? Just having it created with a single record?

Whatever the final validations will be, this should also be made an optional feature into the tablet identified by a setting like such in firebase and tablet local setting. The new validations to consider a survey completed will be false by default and would have to be enabled. Actually the setting would be called "enforce_stricter_school_accreditation_completed_validations" since this would only apply to the school accreditation surveys.

![Screenshot 2022-10-13 153133](https://user-images.githubusercontent.com/1091769/195531320-b1ce68ea-aa02-46f8-b41c-f797294f64c2.jpg)

**Comment by maratomega** [comment]
Hi @ghachey kindly share the rules for validation.

**Comment by ghachey** [comment]
This is currently on hold and we may likely not proceed with this.
